esphome:
  name: petfeeder-test

esp8266:
  board: esp01_1m

wifi:
  ssid: "test"
  password: "testtest"

api:
  custom_services: true
  homeassistant_services: true

external_components:
  - source:
      type: local
      path: ../esphome/components
    components: [petfeeder]

logger:
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

time:
  - platform: sntp
    id: sntp_time

petfeeder:
  time_id: sntp_time
  portions_counter:
    name: "Pet Feeder Portions"
